test push2

diff --git a/.github/workflows/semgrep.yml b/.github/workflows/semgrep.yml
--- a/.github/workflows/semgrep.yml
+++ b/.github/workflows/semgrep.yml
@@ -6,7 +6,9 @@ on:
       - main
     paths:
       - .github/workflows/semgrep.yml
+
 name: Semgrep
+
 jobs:
   buildmavenDepTree:
     runs-on: ubuntu-latest
@@ -28,6 +30,7 @@ jobs:
         with:
           name: mavendeptree
           path: demo/maven_dep_tree.txt
+
   semgrep:
     needs: buildmavenDepTree
     name: Scan
@@ -38,8 +41,22 @@ jobs:
       image: semgrep/semgrep
     steps:
       - uses: actions/checkout@v4
+
       - name: Download artifact from previous job
         uses: actions/download-artifact@v4
         with:
           name: mavendeptree
-      - run:  semgrep ci
+
+      - name: Run Semgrep supply-chain scan and fail on critical/high
+        run: |
+          cd demo
+          # Run supply-chain scan and save output
+          semgrep ci --supply-chain | tee scan_output.txt
+
+          # Fail job if any critical/high vulnerabilities are found
+          if grep -E "CRITICAL|HIGH" scan_output.txt; then
+            echo "Critical/high vulnerability found! Failing the job."
+            exit 1
+          else
+            echo "No critical/high vulnerabilities found."
+          fi
